# Generated by Django 4.1 on 2022-12-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_user_birthdate_user_end_work_date_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.IntegerField(null=True),
        ),
    ]
