# Generated by Django 4.1 on 2023-03-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_brand_name_alter_productcategory_name'),
        ('human_resources', '0003_user_created_at_user_gender_alter_user_end_work_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.branch'),
        ),
    ]
