# Generated by Django 3.2.16 on 2023-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_user_national_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
