# Generated by Django 3.2.16 on 2023-01-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('human_resources', '0005_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='home_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
    ]
