# Generated by Django 4.1 on 2023-01-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_city'),
        ('human_resources', '0006_user_home_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='home_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.role'),
        ),
    ]
