INSERT INTO locations_governorate (id,name) VALUES
(uuid_in(md5(random()::text || random()::text)::cstring), 'القاهرة'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الجيزة'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الأسكندرية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الدقهلية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'البحر الأحمر'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'البحيرة'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الفيوم'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الغربية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الإسماعلية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'المنوفية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'المنيا'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'القليوبية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الوادي الجديد'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'السويس'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'اسوان'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'اسيوط'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'بني سويف'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'بورسعيد'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'دمياط'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الشرقية'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'جنوب سيناء'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'كفر الشيخ'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'مطروح'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'الأقصر'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'قنا'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'شمال سيناء'),
(uuid_in(md5(random()::text || random()::text)::cstring), 'سوهاج');
