# Generated by Django 4.1 on 2023-05-01 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_price', models.FloatField(null=True)),
                ('amount_of_boxes', models.FloatField(null=True)),
                ('amount_of_types', models.IntegerField(null=True)),
                ('amount_of_brands', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiving_date', models.DateField(null=True)),
                ('type', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=400)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.branch')),
                ('location', models.ManyToManyField(to='locations.location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.suppliertype')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField(null=True)),
                ('expire_date', models.DateField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('sold_amount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchasingchannel'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.supplier'),
        ),
    ]
