# Generated by Django 4.1 on 2023-06-07 10:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_phonenumber_branch_deleted_at_branch_is_deleted_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.ManyToManyField(to='purchases.phonenumber'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ManyToManyField(to='inventory.branch'),
        ),
    ]
