# Generated by Django 4.1 on 2023-03-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('inventory', '0002_alter_brand_name_alter_productcategory_name'),
        ('purchases', '0003_rename_type_sellertype_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='Supplier',
        ),
    ]
