# Generated by Django 4.1 on 2023-03-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_rename_seller_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerType',
            new_name='SupplierType',
        ),
    ]
