# Generated by Django 4.1 on 2023-04-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_rename_sellertype_suppliertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasingchannel',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='purchaseproduct',
            name='sold_amount',
            field=models.IntegerField(default=0),
        ),
    ]
