# Generated by Django 4.1 on 2023-02-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='الماركة'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=70, unique=True, verbose_name='النوع'),
        ),
    ]
