# Generated by Django 4.1 on 2022-12-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expire_at',
            field=models.DateField(null=True),
        ),
    ]
