# Generated by Django 3.2.16 on 2023-01-03 10:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_expire_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchasing_price', models.FloatField()),
                ('selling_price', models.FloatField()),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='product_category',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='products',
        ),
        migrations.AlterField(
            model_name='branchphonenumber',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='ProductBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.branch')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price_list',
            field=models.ManyToManyField(to='inventory.PricingList'),
        ),
    ]
