# Generated by Django 3.2.16 on 2023-01-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('inventory', '0003_auto_20230103_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
    ]
