# Generated by Django 3.2.16 on 2023-01-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbranch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='productbranch',
            name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expire_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_list',
        ),
    ]
