# Generated by Django 3.2.16 on 2023-01-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20230120_2008'),
        ('sales', '0006_auto_20230120_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingList',
        ),
        migrations.DeleteModel(
            name='ProductBranch',
        ),
    ]
