# Generated by Django 3.2.16 on 2023-01-21 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.RenameModel(
            old_name='City',
            new_name='Governorate',
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.governorate')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.district'),
        ),
    ]
