# Generated by Django 3.2.16 on 2023-01-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20230121_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='other',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
