# Generated by Django 4.1 on 2023-06-07 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_phonenumber_branch_deleted_at_branch_is_deleted_and_more'),
        ('purchases', '0002_phonenumber_purchase_deleted_at_purchase_is_deleted_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.AlterField(
            model_name='pricinglist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_list', to='purchases.purchaseproduct'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.ManyToManyField(to='sales.phonenumber'),
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ManyToManyField(to='inventory.branch'),
        ),
    ]
