# Generated by Django 4.1 on 2023-04-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customertype',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sellingchannel',
            old_name='type',
            new_name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
