# Generated by Django 3.2.16 on 2023-01-03 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20230103_1238'),
        ('sales', '0003_pricinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.pricinglist'),
        ),
        migrations.DeleteModel(
            name='PricingList',
        ),
    ]
