# Generated by Django 3.2.16 on 2023-01-20 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0007_alter_user_home_location_alter_user_role'),
        ('purchases', '0001_initial'),
        ('locations', '0002_alter_location_city'),
        ('sales', '0005_alter_customer_branch_alter_customer_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='number_of_boxes',
            new_name='amount_of_boxes',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='number_of_types',
            new_name='amount_of_brands',
        ),
        migrations.RemoveField(
            model_name='orderproducts',
            name='price',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ManyToManyField(to='locations.Location'),
        ),
        migrations.AddField(
            model_name='order',
            name='amount_of_types',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='create_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='human_resources.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproducts',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseproduct'),
        ),
        migrations.CreateModel(
            name='PricingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selling_price', models.FloatField()),
                ('end_date', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaseproduct')),
            ],
        ),
    ]
